# Generated by Django 5.0 on 2024-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_read_time_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
