# Generated by Django 5.0 on 2024-01-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_of_origin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_of_residence',
        ),
    ]
