# Generated by Django 4.2.6 on 2024-01-23 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=150)),
                ('client_secret', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('response_type', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('grant_types', models.CharField(max_length=200)),
                ('redirect_uris', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
